# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BMI_Calculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BMI_Calculator
  # add pods for desired Firebase products
  pod 'Firebase'
  pod 'Firebase/Database'
  # https://firebase.google.com/docs/ios/setup#available-pods

end
