# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDo_List_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDo_List_App
  # add the Firebase pod for Google Analytics
  #pod 'Firebase/Analytics'

  # add the Firebase pod for Database and Core functionalities
  pod 'Firebase/Database'
  pod 'Firebase/Core'

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'ToDo_List_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDo_List_AppUITests' do
    # Pods for testing
  end

end
